### ISSUE TITLE
Installation: update

### ISSUE THREAD

**Issue by mickael-kerjean** [mickael-kerjean/nuage#71]
Had an email report: Intall errors on windows and EC2. Have to provide more info for the install and udpate the doc accordingly

**Comment by otesuji** [comment]
Thanks Mickael. I'm the one who wrote you.

**here are the results of the npm install:**

```
C:\Users\Vincent\nuage>npm install
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN less-loader@4.1.0 requires a peer of less@^2.3.1 || ^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN url-loader@0.6.2 requires a peer of file-loader@* but none is installed. You must install peer dependencies yourself.
npm WARN webpack-dev-server@3.1.4 requires a peer of webpack@^4.0.0-beta.1 but none is installed. You must install peer dependencies yourself.
npm WARN webpack-dev-middleware@3.1.3 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

up to date in 50.621s

```

**and obviously after the npm run build:**

```
> NODE_ENV=production webpack -p

'NODE_ENV' n’est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nuage@0.0.0 build: `NODE_ENV=production webpack -p`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nuage@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Vincent\AppData\Roaming\npm-cache\_logs\2018-05-18T08_11_22_648Z-debug.log
```

this was on windows , but kind of the same problem on linux (ec2)

Thanks.
Vincent

**Comment by otesuji** [comment]
and for info the node server/index.js after that:


```
C:\Users\Vincent\nuage>node server/index.js
module.js:549
    throw err;
    ^

Error: Cannot find module '../build/Debug/nodegit.node'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Vincent\nuage\node_modules\nodegit\dist\nodegit.js:19:12)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Vincent\nuage\server\model\backend\git.js:1:81)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Vincent\nuage\server\model\files.js:8:10)
    at Module._compile (module.js:652:30)
```

**Comment by mickael-kerjean** [comment]
I got some thought about this and made a few tests and I think it would be a much better idea to provide prebuild packages: deb, rpm, AUR.

That would make things much faster to install, and much easier without having to copy and paste a boring list of instructions. What do you think?

**Comment by otesuji** [comment]
preferred the 'standard' procedure

**Comment by otesuji** [comment]
by the way, tried the Termux one and it wroks perfectly!

**Comment by mickael-kerjean** [comment]
I'm working on a similar script for ubuntu/debian. It's taking quite some time as there's a dependency that is pretty tricky to install depending on the system, version of node, ...

Should be out soon. Termux is nice but having nuage available on a proper server makes things much faster

**Comment by mickael-kerjean** [comment]
I sent you a message with the installation details, if you have any issue, we can continue the discussion over email.

I've decided to provide support for installation on bare metal only to those supporting the project via our [patreon page](https://patreon.com/mickaelk). The reason for this is maintaining installation for all possible environments is time consuming to both create and maintain and this time could be better use to develop new features.

The installation with docker and tmux will remain maintained as part of the open source work.
